import "./globals.css";
import { Navigation } from "../../components/navigation";
import { Poppins, Roboto } from "next/font/google";
import { Provider } from "../../components/provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const roboto = Roboto({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
  weight: ["100", "300", "400", "500", "700", "900"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${poppins.variable} ${roboto.variable}`}>
      <body className="relative">
        <Provider>
          {/* <Navigation /> */}
          {children}
        </Provider>
      </body>
    </html>
  );
}
